### PR TITLE
fix(cmd): installs to current ns when --local mode used and no ns defined

### LINKED ISSUE #306: Local operator installation should take current namespace into consideration
##### Issue Overview

`ike install-operator -l|--local` installs operator to the local namespace. When `-n|--namespace` is not specified, however, it will default to `istio-workspace-operator` instead of the current active namespace (or project)

##### Expected Behaviour

Installs to the current namespace.

##### Current Behaviour

Installs to the `istio-workspace-operator` default namespace

##### Steps To Reproduce

1. Create new namespace|project
2. `ike install-operator -l` without specifying the namespace.

### PR DESCRIPTION
**Pull request by bartoszmajsak**
#### Short description of what this resolves:

when `ike install-operator -l` is invoked it will install operator to the current namespace instead of `istio-workspace` default one which is intended for global.

#### Changes proposed in this pull request:

- fix in the `install-operator` command
- e2e test covering local install path (I had quite a hard time figuring out how to test in more fine-grained level - e.g. using fake client or gock with stubbed calls. Those two paths seemed to be more expensive)

Fixes #306

### CODE REVIEW

File: e2e/operator_installation_test.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+	Context("local installation", func() {
+
+		It("install ike operator into specified namespace", func() {
+			// given
+			projectName := "ike-local-installation-defined-namespace-" + naming.RandName(16)
+			<-testshell.Execute(NewProjectCmd(projectName)).Done()
+			defer func() {
+				<-testshell.Execute(DeleteProjectCmd(projectName)).Done()
+			}()
+			PushOperatorImage(projectName)
```
Comment (bartoszmajsak) [inline e2e/operator_installation_test.go]: I think it's time we should optimize it and have a shared image built as the previous step of the pipeline. WDYT?

File: e2e/smoke_test.go [hunk 2]
```diff
@@ -78,7 +78,8 @@ var _ = Describe("Smoke End To End Tests - against OpenShift Cluster with Istio
 			<-testshell.Execute(NewProjectCmd(namespace)).Done()
 
 			UpdateSecurityConstraintsFor(namespace)
-			DeployLocalOperator(namespace)
+			PushOperatorImage(namespace)
+			InstallLocalOperator(namespace)
```
Comment (bartoszmajsak) [inline e2e/smoke_test.go]: Split into two steps as I need to push the image for the `install-operator` tests and only then invoke it in different flavours.

File: e2e/operator_installation_test.go (hunk 1 above)
Comment (aslakknutsen) [reply e2e/operator_installation_test.go]:
```
build operator image
build test images

test
  tag/push operator image to ns
  tag/push test image to ns
```

?

File: e2e/operator_installation_test.go [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+
+			// when
+			<-testshell.Execute("ike install-operator -l -n " + projectName).Done()
```
Comment (aslakknutsen) [inline e2e/operator_installation_test.go]: call InstallLocalOperator(ns)?

File: e2e/operator_installation_test.go [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+			// given
+			projectName := "ike-local-installation-defined-namespace-" + naming.RandName(16)
+			<-testshell.Execute(NewProjectCmd(projectName)).Done()
+			defer func() {
+				<-testshell.Execute(DeleteProjectCmd(projectName)).Done()
+			}()
+			PushOperatorImage(projectName)
+
+			// when
+			<-testshell.Execute("ike install-operator -l").Done()
```
Comment (aslakknutsen) [inline e2e/operator_installation_test.go]: call InstallLocalOperator(nil)?

File: e2e/operator_installation_test.go (hunk 3 above)
Comment (bartoszmajsak) [reply e2e/operator_installation_test.go]: Sure, but isn't it hiding q bit the actual subject of the test?

File: e2e/operator_installation_test.go (hunk 1 above)
Comment (bartoszmajsak) [reply e2e/operator_installation_test.go]: I was thinking about pushing to public repo so that we avoid test-level pushes too

Comment (aslakknutsen) [reply e2e/operator_installation_test.go]: Yeah, I was about to comment if we should just push to quay. I'm good with that.

File: pkg/cmd/install/install.go [hunk 5]
```diff
@@ -48,11 +50,24 @@ func installOperator(cmd *cobra.Command, args []string) error { //nolint[:unpara
...
 	}
 
+	if local && !cmd.Flags().Changed("namespace") {
+		kubeCfg := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
+			clientcmd.NewDefaultClientConfigLoadingRules(),
+			&clientcmd.ConfigOverrides{},
+		)
+
+		if namespace, _, err = kubeCfg.Namespace(); err != nil {
+			log.Error(err, "failed to read k8s config")
```
Comment (aslakknutsen) [inline pkg/cmd/install/install.go]: Maybe make the error something like: Failed to read kubeconf 'config file path' to get the current namespace, please provide a namespace manually via -namespace?

File: e2e/operator_installation_test.go (hunk 1 above)
Comment (bartoszmajsak) [reply e2e/operator_installation_test.go]: Created #313

File: e2e/operator_installation_test.go [hunk 6]
```diff
@@ -0,0 +1,80 @@
+package e2e_test
+
+import (
+	"fmt"
```
Comment (golangcibot) [inline e2e/operator_installation_test.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
	"fmt"

```

File: pkg/cmd/install/install.go (hunk 5 above)
Comment (bartoszmajsak) [reply pkg/cmd/install/install.go]: Oh, I missed that one. Providing PR in a minute. #314
