### PR TITLE
fix: enables use of IKE_CONFIG env var to pass config file

### LINKED ISSUE #274: Unable to specify config file through env variable
##### Issue Overview

The only way to define different config file than default `.ike.config.yaml` is by `-c|--config` flag. It should be however possible to overwrite its location by using `IKE_CONFIG` env variable.

##### Expected Behaviour

`IKE_CONFIG` should take precedence over.

##### Current Behaviour

Not possible to use `IKE_CONFIG`.

### PR DESCRIPTION
**Pull request by bartoszmajsak**
Fixes #274

### CODE REVIEW

File: pkg/cmd/config/config.go [hunk 1]
```diff
@@ -27,13 +36,9 @@ import (
...
-func SetupConfigSources(configFile string, notDefault bool) error {
-	viper.Reset()
-	viper.SetEnvPrefix("IKE")
-	viper.AutomaticEnv()
-	viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
-	viper.SetTypeByDefaultValue(true)
-
+func SetupConfigSources(configFile string, defaultConfigFile bool) error {
+	println(configFile)
+	println(defaultConfigFile)
```
Comment (aslakknutsen) [inline pkg/cmd/config/config.go]: ?

Comment (bartoszmajsak) [reply pkg/cmd/config/config.go]: LOL, suggestion would help here haha

Comment (bartoszmajsak) [reply pkg/cmd/config/config.go]: Fixed with 96ba756

File: e2e/smoke_test.go [hunk 2]
```diff
@@ -191,7 +191,8 @@ var _ = Describe("Smoke End To End Tests - against OpenShift Cluster with Istio
 		// Thus it treats cluster as vanilla k8s and expects Deployment, not DeploymentConfig to appear
 		// Enable when https://github.com/telepresenceio/telepresence/issues/1139 is fixed
 		XContext("openshift deploymentconfig", func() {
-			BeforeEach(func() {
+
+      BeforeEach(func() {
```
Comment (golangcibot) [inline e2e/smoke_test.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
			BeforeEach(func() {
```
