### PR TITLE
fix(operator): avoid reusing version in clone name

### LINKED ISSUE #683: Telepresence can't find pods with long version string
##### Issue Overview

When running the `ike develop` command it consistently fails with the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 49, in main
    start_proxy = proxy.setup(runner, args)
  File "/usr/local/bin/telepresence/telepresence/proxy/proxy.py", line 157, in setup
    operation.prepare(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/operation.py", line 282, in prepare
    pod = get_pod_for_deployment(runner, deployment)  # type: Manifest
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 266, in get_pod_for_deployment
    raise RuntimeError(
RuntimeError: Telepresence pod not found for Deployment 'tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176ed-humphrey'.
```

The telepresence logs repeatedly complain about not being able to find the pods even though they spin up correctly:
```
 120.3 TEL | [98] captured in 0.29 secs.
 120.3 TEL | Checking tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176hvxtd
 120.3 TEL | --> Name does not match
 120.3 TEL | Checking tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176pv645
 120.3 TEL | --> Name does not match
 120.3 TEL | Checking tpserver-deployment-5678b07dcbecd08b3b6beaf5287302ef51a176ttkh7
 120.3 TEL | --> Name does not match
 120.3 TEL | END SPAN remote.py:229(get_pod_for_deployment)  119.5s
```

I believe this is due to us using commit SHA for the version meaning that the expected pod name is longer than supported 63 characters so is truncated. As telepresence tries to match the pods that start with the deployment name it is never able to find them.

##### Expected Behaviour

Telepresence to find the pods.

##### Current Behaviour

Telepresence is unable to find the pods due to their name being too long.

##### Steps To Reproduce

I haven't fully tested the theory but it should be possible to reproduce by trying to develop on a deployment with a long version string.

---

I can't tell if this is an issue with this repo or telepresence but I'm happy to go and fix this if you could point me to the place where the deployment name is decided. I imagine that truncating version numbers would be a suitable fix for this?

### PR DESCRIPTION
**Pull request by aslakknutsen**
The version number could be very long so only expose
a short sha version of it in the clone name.

Fixes #683

### CODE REVIEW

File: pkg/k8s/deployment_test.go [hunk 1]
```diff
@@ -139,7 +139,7 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
 			mutatorErr := k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &ref)
 			Expect(mutatorErr).ToNot(HaveOccurred())
 
-			d := get.Deployment(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
+			d := get.Deployment(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:142]:
```suggestion
			d := get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 2]
```diff
@@ -148,15 +148,15 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
 			mutatorErr := k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &ref)
 			Expect(mutatorErr).ToNot(HaveOccurred())
 
-			_ = get.Deployment(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
+			_ = get.Deployment(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:151]:
```suggestion
			_ = get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 3]
```diff
@@ -148,15 +148,15 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
...
 		})
 
 		It("should remove liveness probe from cloned deployment", func() {
 			ref := CreateTestRef()
 			mutatorErr := k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &ref)
 			Expect(mutatorErr).ToNot(HaveOccurred())
 
-			deployment := get.Deployment(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
+			deployment := get.Deployment(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:159]:
```suggestion
			deployment := get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 4]
```diff
@@ -165,7 +165,7 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
...
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:168]:
```suggestion
			deployment := get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 5]
```diff
@@ -174,17 +174,17 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
...
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:177]:
```suggestion
			deployment := get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 6]
```diff
@@ -174,17 +174,17 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
...
+			Expect(deployment.Spec.Selector.MatchLabels["version"]).To(BeEquivalentTo(model.GetSha("v1") + "-test"))
 		})
 
 		It("should only mutate if Target is of kind Deployment", func() {
 			notMatchingRef := model.Ref{Name: "test-ref", Targets: []model.LocatedResourceStatus{model.NewLocatedResource("Service", "test-ref", nil)}}
 			mutatorErr := k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &notMatchingRef)
 			Expect(mutatorErr).ToNot(HaveOccurred())
 
-			_, err := get.DeploymentWithError(ctx.Namespace, notMatchingRef.Name+"-v1-"+ctx.Name)
+			_, err := get.DeploymentWithError(ctx.Namespace, notMatchingRef.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:187]:
```suggestion
			_, err := get.DeploymentWithError(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 7]
```diff
@@ -195,21 +195,21 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
 			mutatorErr := k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &ref)
 			Expect(mutatorErr).ToNot(HaveOccurred())
 
-			deployment := get.Deployment(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
-			Expect(deployment.Spec.Selector.MatchLabels["version"]).To(BeEquivalentTo("v1-test"))
+			deployment := get.Deployment(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:198]:
```suggestion
			deployment := get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 8]
```diff
@@ -195,21 +195,21 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
...
+			Expect(deployment.Spec.Selector.MatchLabels["version"]).To(BeEquivalentTo(model.GetSha("v1") + "-test"))
 
 			// when Deployment is deleted
 			c.Delete(ctx, &deployment)
 
-			_, err := get.DeploymentWithError(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
+			_, err := get.DeploymentWithError(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:204]:
```suggestion
			_, err := get.DeploymentWithError(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 9]
```diff
@@ -195,21 +195,21 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
...
 			Expect(err).To(HaveOccurred())
 
 			// then it should be recreated on next reconcile
 			mutatorErr = k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &ref)
 			Expect(mutatorErr).ToNot(HaveOccurred())
 
-			deployment = get.Deployment(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
-			Expect(deployment.Spec.Selector.MatchLabels["version"]).To(BeEquivalentTo("v1-test"))
+			deployment = get.Deployment(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:211]:
```suggestion
			deployment = get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 10]
```diff
@@ -219,7 +219,7 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
 				mutatorErr := k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &ref)
 				Expect(mutatorErr).ToNot(HaveOccurred())
 
-				deployment := get.Deployment(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
+				deployment := get.Deployment(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:222]:
```suggestion
				deployment := get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 11]
```diff
@@ -228,7 +228,7 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
...
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:231]:
```suggestion
				deployment := get.Deployment(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 12]
```diff
@@ -244,7 +244,7 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
 				mutatorErr := k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &ref)
 				Expect(mutatorErr).ToNot(HaveOccurred())
 
-				_, err := get.DeploymentWithError(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
+				_, err := get.DeploymentWithError(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:247]:
```suggestion
				_, err := get.DeploymentWithError(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 13]
```diff
@@ -290,13 +290,13 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
 			mutatorErr := k8s.DeploymentMutator(template.NewDefaultEngine())(ctx, &ref)
 			Expect(mutatorErr).ToNot(HaveOccurred())
 
-			_, mutatedFetchErr := get.DeploymentWithError(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
+			_, mutatedFetchErr := get.DeploymentWithError(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:293]:
```suggestion
			_, mutatedFetchErr := get.DeploymentWithError(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/k8s/deployment_test.go [hunk 14]
```diff
@@ -290,13 +290,13 @@ var _ = Describe("Operations for k8s Deployment kind", func() {
...
 			Expect(mutatedFetchErr).ToNot(HaveOccurred())
 
 			revertorErr := k8s.DeploymentRevertor(ctx, &ref)
 			Expect(revertorErr).ToNot(HaveOccurred())
 
-			_, revertedFetchErr := get.DeploymentWithError(ctx.Namespace, ref.Name+"-v1-"+ctx.Name)
+			_, revertedFetchErr := get.DeploymentWithError(ctx.Namespace, ref.Name+"-"+model.GetSha("v1")+"-"+ctx.Name)
```
Comment (bartoszmajsak) [inline pkg/k8s/deployment_test.go:299]:
```suggestion
			_, revertedFetchErr := get.DeploymentWithError(ctx.Namespace, ref.GetNewVersion(ctx.Name))
```

File: pkg/model/model.go [hunk 15]
```diff
@@ -199,6 +200,12 @@ func (r *Ref) GetResources(predicate Predicate) []ResourceStatus {
 	return refs
 }
 
+func GetSha(version string) string {
```
Comment (bartoszmajsak) [inline pkg/model/model.go:203]:
```suggestion
// GetSha computes hash of a version and returns 8 characters substring of it.
func GetSha(version string) string {
```

**Review by bartoszmajsak — APPROVED** [review]
